{% set name = "quilt" %}
{% set pname = "quilt3" %}
{% set version = "3.1.1" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://github.com/quiltdata/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 84918bf8a3f0b3fe93db708bb142c8b6158c5240a2c5c780dbabd5b3cb8c6566

build:
  number: 0
  skip: true  # [py2k]
  script: 
      - cd api/python
      - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs >=1.4.0
    - aws-requests-auth >=0.4.2
    - boto3 >=1.8.0 
    - elasticsearch 6.3.1
    - jsonlines 1.2.0
    - packaging >=16.8
    - pandas >=0.19.2
    - pyarrow 0.13               # as of 7/5/19: linux/circleci bugs on 0.14
    - requests >=2.12.4
    - urllib3 1.24               # required by requests
    - ruamel.yaml <=0.15.70
    - tqdm >=4.26.0
    - xattr >=0.9.6  # [not win]
    - humanize

test:
  imports:
    - quilt3

about:
  home: https://quiltdata.com/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Quilt: where data comes together'

  description: |
    Quilt is infrastructure for data-driven teams to store, version, deploy and iterate on models and data.
    Data in Quilt are visual, discoverable, and reproducible.
  dev_url: https://github.com/quiltdata/quilt

extra:
  recipe-maintainers:
    - knaaptime
    - akarve
