{% set name = "quilt" %}
{% set pname = "quilt3" %}
{% set version = "6.1.1" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://github.com/quiltdata/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d0be9f000e64b204f9de81be398bdfb6b70d265e0b5e9853b34e1529ac7ac43f

build:
  number: 1
  noarch: python
  script:
    - cd api/python
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - platformdirs >=2
    - aws-requests-auth >=0.4.2
    - boto3 >=1.10.0
    - jsonlines 1.2.0
    - requests >=2.12.4
    - requests-futures ==1.0.0
    - pyyaml >=5.1
    - tqdm >=4.32
    - tenacity >=5.1.1
    - jsonschema >=3,<5
    - pydantic >=2.0.0,<3.0.0

test:
  imports:
    - quilt3
  requires:
    - pip
    - setuptools >=61.0
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://quiltdata.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Quilt: where data comes together'

  description: |
    Quilt is infrastructure for data-driven teams to store, version, deploy and iterate on models and data.
    Data in Quilt are visual, discoverable, and reproducible.
  dev_url: https://github.com/quiltdata/quilt

extra:
  recipe-maintainers:
    - knaaptime
    - akarve
