travis:
  secure:
    BINSTAR_TOKEN: Y4Qc3HZkZ5iFIG/HQ2Gviu1WKFtBttdvGpdcqgZkXpRPGtynhHWNG7DP/UILstJoN4E+FifQMQ91CyY+el3ETvGvoubP4OqhTkw37PZj3ZnwN/yI0/PlWToKPi/2xGMPrOcbiJR4NQ1JC0/UZhQUrq4H5guvWRqvtm1r6l/VD/1ajPUvYf5pLRgsTbsOF7bdsk5jHqjEjd7oiOoDT9w++DVTpmXpbXpNdJhWZH0mvmn1dOvOT7LjWz4YaTVEvW/QpxmKHvogXn/bPhpWJbyMJUOtfPRBRJYzSvboPViprnAB+D9UCSEK3kWy9WskGAS+aYunnEgkbAZ/BydwZUOo6LVFfNLAymrn4B10N0+KnMpsN3XSukBSOT4O5Ov6NrgRt8bDO0mEoRvge77mAacWq5ZKfUIGqaSvNdIiidEvHz8kmzwjuiNfJn6qs17059LxrgGQihSOOBO2mqw9ud+DX9X/QsPlD8EWUEXKRf3X2a4n3BBTFMWeE4ErKmHf47Z7fLh/RhEBuipNjEpVC6qoyPY6dihJ0MehKdqeiSDSn557EHUFHY0WkNRgDvJo7+IUnwJHyxcHJ9273rPFbzf4nEtsQ01+uwdYsD11G9utgd6PEbLEa6494yLlvDtbu9zAFgB+wzQita9rolSjos8n+3bgiKkQsB+WH5ZwksLoick=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
